dataset:
  images: 'D:/semester 1 study/Goettingen study material/Practical Course Data Fusion/dataset/images'
  videos: 'D:/semester 1 study/Goettingen study material/Practical Course Data Fusion/dataset/videos'